
from Tkinter import *
def npiz():
    from Tkinter import *
    top=Tk()
    top.title("Round Pizza Table : The Last Honest Pizza")
    canvas=Canvas(width=530,height=150,bg='white')
    canvas.pack(expand=YES,fill=BOTH)
    gif1=PhotoImage(file='C:\Users\Sourav\Desktop\Project Python\qw.gif')
    canvas.create_image(50,10,image=gif1,anchor=NW)
    frame=Frame(top)
    frame.pack(anchor=CENTER,pady=20)
    L1=Label(frame, text="Name")
    L1.pack()
    E1=Entry(frame,bd=5)
    E1.pack(pady=5)
    mb=  Menubutton (frame,text="Pizaa Type", relief=RAISED )
    mb.grid(pady=5)
    mb.menu  =  Menu ( mb, tearoff = 0 )
    mb["menu"]  =  mb.menu
    spVar  = IntVar()
    mpVar = IntVar()
    lpVar = IntVar()
    mb.menu.add_checkbutton ( label="Small",variable=spVar)
    mb.menu.add_checkbutton ( label="Medium",variable=mpVar )
    mb.menu.add_checkbutton ( label="Large",variable=lpVar)
    mb.pack(pady=5)
    L4=Label(frame, text="Mobile Number")
    L4.pack()
    E4=Entry(frame,bd=5)
    E4.pack(pady=5)
    L5=Label(frame, text="Email Id")
    L5.pack()
    E5=Entry(frame,bd=5)
    E5.pack(pady=5)
    rb=Button(frame,text="Order Now",fg="black")
    rb.pack(side=RIGHT,pady=5)
    top.geometry("530x450")
    top.resizable(width=False, height=False)
    top.mainloop()
    
def tp():
    from Tkinter import *
    top=Tk()
    top.title("Round Pizza Table : The Last Honest Pizza")
    canvas=Canvas(width=530,height=150,bg='white')
    canvas.pack(expand=YES,fill=BOTH)
    gif1=PhotoImage(file='C:\Users\Sourav\Desktop\Project Python\q.gif')
    canvas.create_image(50,10,image=gif1,anchor=NW)
    frame=Frame(top)
    frame.pack(anchor=CENTER,pady=20)
    L1=Label(frame, text="Order Id")
    L1.pack()
    E1=Entry(frame,bd=5)
    E1.pack(pady=5)
    rb=Button(frame,text="Track Now",fg="black")
    rb.pack(side=RIGHT,pady=5)
    top.geometry("530x450")
    top.resizable(width=False, height=False)
    top.mainloop()
    
def cpiz():
    from Tkinter import *
    top=Tk()

    top.title("Round Pizza Table : The Last Honest Pizza")
    canvas=Canvas(width=530,height=150,bg='white')
    canvas.pack(expand=YES,fill=BOTH)
    gif1=PhotoImage(file='C:\Users\Sourav\Desktop\Project Python\q.gif')
    canvas.create_image(50,10,image=gif1,anchor=NW)
    frame=Frame(top)
    frame.pack(anchor=CENTER,pady=20)
    L1=Label(frame, text="Name")
    L1.pack(pady=5)
    E1=Entry(frame,bd=5)
    E1.pack()
    L2=Label(frame, text="Order ID")
    L2.pack(pady=5)
    E2=Entry(frame,bd=5)
    E2.pack()
    rb=Button(frame,text="Cancel Now",fg="black")
    rb.pack(side=LEFT,pady=5)
    top.geometry("530x450")
    top.resizable(width=False, height=False)
    top.mainloop()


top=Tk()
top.title("Round Pizza Table : The Last Honest Pizza")
canvas=Canvas(width=530,height=150,bg='white')
canvas.pack(expand=YES,fill=BOTH)
gif1=PhotoImage(file='C:\Users\Sourav\Desktop\Project Python\q.gif')
canvas.create_image(50,10,image=gif1,anchor=NW)
frame=Frame(top)
frame.pack(anchor=CENTER,pady=20)
rb=Button(frame,text="ORDER PIZZA",fg="black",command=npiz)
rb.pack(pady=5)
bb=Button(frame,text="CANCEL ORDER",fg="black",command=cpiz)
bb.pack(pady=5)
gb=Button(frame,text="TRACK ORDER",fg="black",command=tp)
gb.pack(pady=5)
top.geometry("530x450")
top.resizable(width=False, height=False)
top.mainloop()
