from Tkinter import *
top=Tk()
top.title("Round Pizza Table : The Last Honest Pizza")
canvas=Canvas(width=530,height=150,bg='white')
canvas.pack(expand=YES,fill=BOTH)
gif1=PhotoImage(file='C:\Users\Sourav\Desktop\Project Python\q.gif')
canvas.create_image(50,10,image=gif1,anchor=NW)
frame=Frame(top)
frame.pack(anchor=CENTER,pady=20)
L1=Label(frame, text="Order Id")
L1.pack()
E1=Entry(frame,bd=5)
E1.pack(pady=5)

rb=Button(frame,text="Track Now",fg="black")
rb.pack(side=RIGHT,pady=5)
top.geometry("530x450")
top.resizable(width=False, height=False)
top.mainloop()
